name: fire_tv_listener
description: Widget to listen to events from a Fire TV Remote Control.
version: 0.0.4
homepage: https://pub.dev/packages/fire_tv_listener
repository: https://github.com/jeffmikels/flutter_fire_tv_listener

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
